[app]
app_name = "cloud-export"
app_mode = "release" #运行方式 release 线上模式  debug 开发模式
port = "0.0.0.0:80"  #http 运行端口
http_listen = "0.0.0.0:30080" #http 健康检测端口
is_sso = false   #是否开启单点登录
params = false
logger = "/home/logs/app"
version = "1.0.0"

[mysql]
dsn = "root:123456@tcp(127.0.0.1:3306)/export?charset=utf8&parseTime=True&loc=Local"
prefix = "b_"  ##表前缀
db_name = "export" #表名
max_idle_conn = 10
max_open_conn = 100
conn_max_lifetime = 6

[redis]
addr = "127.0.0.1:6379"
db = 10
password = ""
min_idle_conns = 5
pool_size = 500
pool_timeout = 2
idle_timeout = 10
token_expired = 7200 # expired time 2*60*60

[upload]
file_url="upload_file"

[task_pool]
http_worker=5
row_worker=5